---
title: "PROJET TUTORÉ"
author: "RAMDÉ Ismaïl"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Chargement des librairies
```{r}
library(readxl)
library(tidyr)
library(tidyverse)
library(survival)
library(lcmm)
```


# Chargement des données
```{r}
data = read_xlsx("measures_pmi.xlsx")
head(data)
str(data)
summary(data)
```

# deuxieme jeu de données

```{r}
library(lcmm)
data_poids = read_xlsx("poids.xlsx")
data_poids$date_first=as.Date(data_poids$date_first)
summary(data_poids)
```

```{r}
ggplot(data = data_poids)+geom_point(aes(x = date_first,y=ttaille_first,color=sexe))
ggplot(data = data_poids)+geom_point(aes(x = date_last,y=ttaille_last,color=sexe))
```

```{r}
ggplot(data = data_poids)+geom_point(aes(x = date_first,y=ttaille_first,color=sexe))
ggplot(data = data_poids)+geom_point(aes(x = date_first,y=ttaille_first,color=sexe))
```

**Un peu du pre-processing**

```{r}
data_poids$mmuscle_first = as.numeric(data_poids$mmuscle_first)
data_poids$mgrasse_first = as.numeric(data_poids$mgrasse_first)
data_poids$mgrasse_last = as.numeric(data_poids$mgrasse_last)
data_poids$mmuscle_last = as.numeric(data_poids$mmuscle_last)
data_poids$mmuscle_postfirst = as.numeric(data_poids$mmuscle_postfirst)
data_poids$mgrasse_postfirst = as.numeric(data_poids$mgrasse_postfirst)
data_poids$mmuscle_postlast =  as.numeric(data_poids$mmuscle_postlast)
data_poids$mgrasse_postlast = as.numeric(data_poids$mgrasse_postlast)

data_poids <- data_poids %>%
     mutate(mmuscle_first=replace_na(mmuscle_first, median(mmuscle_first, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mgrasse_first=replace_na(mgrasse_first, median(mgrasse_first, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mgrasse_last=replace_na(mgrasse_last, median(mgrasse_last, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mmuscle_last=replace_na(mmuscle_last, median(mmuscle_last, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mmuscle_postfirst=replace_na(mmuscle_postfirst, median(mmuscle_postfirst, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mgrasse_postfirst=replace_na(mgrasse_postfirst, median(mgrasse_postfirst, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mmuscle_postlast=replace_na(mmuscle_postlast, median(mmuscle_postlast, na.rm=TRUE)))
data_poids <- data_poids %>%
     mutate(mgrasse_postlast=replace_na(mgrasse_postlast, median(mgrasse_postlast, na.rm=TRUE)))
```

```{r}
data_poids_clean = write_csv(data_poids,"data_poids_clean.csv")
```


```{r}
data_mod = read.csv("data_df.csv")
data_mod$month=  as.numeric(format(as.Date(data_mod$date),format="%m"))
```


Méthode 1 : Modèle simple

```{r}
model_lcmm = function(formula,data_mod,nclass){
  model = lcmm(formula, random = ~ month, subject = "idPatient", 
               data = data_mod, ng = nclass,mixture = ~month,link = "splines",
               B = lcmm(formula,random = ~ month, subject = "idPatient", 
               data = data_mod, ng = 1,link = "splines"))
  return(model)
}
model_predict = function(model_name,newdata){
  pred = predictY(model_name,newdata,var.time = "month")
  }
```

Mèthode 2 : Modèle multiple

```{r}
model_lcmm_multiple = function(formula,data_mod,nclass){
 model = multlcmm(formula, random =~ month, 
                 subject = "idPatient",ng=nclass,randomY = TRUE,cor = BM(month), 
                 link="splines",mixture= ~month,data = as.data.frame(data_mod),
                 B = multlcmm(formula, random =~ month, 
                 subject = "idPatient",ng=1,randomY = TRUE,cor = BM(month), 
                 link="splines",data = as.data.frame(data_mod))
                )
 return (model)
}
```


```{r}
model_tt_2 = model_lcmm(as.formula("ttaille ~ month"),data_mod,nclass = 2)
model_tt_3 = model_lcmm(as.formula("ttaille ~ month"),data_mod,nclass = 3)
model_tt_4 = model_lcmm(as.formula("ttaille ~ month"),data_mod,nclass = 4)
model_tt_5 = model_lcmm(as.formula("ttaille ~ month"),data_mod,nclass = 5)
s_tt = summarytable(model_tt_2,model_tt_3,model_tt_4,model_tt_5)
```


Modèle avec masse grasse

```{r}
model_mg_2 = model_lcmm(as.formula("mgrasse ~ month"),data_mod,nclass = 2)
model_mg_3 = model_lcmm(as.formula("mgrasse ~ month"),data_mod,nclass = 3)
model_mg_4 = model_lcmm(as.formula("mgrasse ~ month"),data_mod,nclass = 4)
model_mg_5 = model_lcmm(as.formula("mgrasse ~ month"),data_mod,nclass = 5)
s_mg = summarytable(model_mg_2,model_mg_3,model_mg_4,model_mg_5)
s_mg
```

```{r}
model_mm_2 = model_lcmm(as.formula("mmuscle ~ month"),data_mod,nclass = 2)
model_mm_3 = model_lcmm(as.formula("mmuscle ~ month"),data_mod,nclass = 3)
model_mm_4 = model_lcmm(as.formula("mmuscle ~ month"),data_mod,nclass = 4)
model_mm_5 = model_lcmm(as.formula("mmuscle ~ month"),data_mod,nclass = 5)
s_mm = summarytable(model_mm_2,model_mm_3,model_mm_4,model_mm_5)
s_mm
```

# Ici on trace les modèles optimaux.

```{r}
model_tt_4$call$fixed = as.formula("ttaille~month")
model_mg_3$call$fixed = as.formula("mgrasse~month")
model_mm_4$call$fixed = as.formula("mmuscle~month")
```

```{r}
newdata = data.frame(month=seq(1,12,length=792))
# classe 4
pred_tt = model_predict(model_tt_4,newdata)
# classe 3
pred_mg = model_predict(model_mg_3,newdata)
# classe 2
pred_mm = model_predict(model_mm_4,newdata)
plot(pred_tt,main="Tour de taille",lty=1)
plot(pred_mg,main="Masse grasse",lty=1)
plot(pred_mm,main="Masse musculaire",lty=1)
```


Mèthode 2 : modéle multiple

```{r}
formula_ttmg = as.formula("ttaille+mgrasse~month")
formula_ttmm = as.formula("ttaille+mmuscle~month")
model_ttmg_2 = model_lcmm_multiple(formula_ttmg,data_mod,nclass = 2)
model_ttmg_3 = model_lcmm_multiple(formula_ttmg,data_mod,nclass = 3)
model_ttmg_4 = model_lcmm_multiple(formula_ttmg,data_mod,nclass = 4)
model_ttmg_5 = model_lcmm_multiple(formula_ttmg,data_mod,nclass = 5)
s_tt_mg = summarytable(model_ttmg_2,model_ttmg_3,model_ttmg_4,model_ttmg_5)
```

```{r}
model_ttmm_2 = model_lcmm_multiple(formula_ttmm,data_mod,nclass = 2)
model_ttmm_3 = model_lcmm_multiple(formula_ttmm,data_mod,nclass = 3)
model_ttmm_4 = model_lcmm_multiple(formula_ttmm,data_mod,nclass = 4)
model_ttmm_5 = model_lcmm_multiple(formula_ttmm,data_mod,nclass = 5)
s_tt_mm = summarytable(model_ttmm_2,model_ttmm_3,model_ttmm_4,model_ttmm_5)
```

```{r}
formula_mmmg = as.formula("mgrasse+mmuscle~month")
model_mgmm_2 = model_lcmm_multiple(formula_mmmg,data_mod,nclass = 2)
model_mgmm_3 = model_lcmm_multiple(formula_mmmg,data_mod,nclass = 3)
model_mgmm_4 = model_lcmm_multiple(formula_mmmg,data_mod,nclass = 4)
model_mgmm_5 = model_lcmm_multiple(formula_mmmg,data_mod,nclass = 5)
s_tt_mmmg = summarytable(model_mgmm_2,model_mgmm_3,model_mgmm_4,model_mgmm_5)
```


```{r}
formula_ttmmmg = as.formula("ttaille+mgrasse+mmuscle~month")
model_ttmmmg_2 = model_lcmm_multiple(formula_ttmmmg,data_mod,nclass = 2)
model_ttmmmg_3 = model_lcmm_multiple(formula_ttmmmg,data_mod,nclass = 3)
model_ttmmmg_4 = model_lcmm_multiple(formula_ttmmmg,data_mod,nclass = 4)
model_ttmmmg_5 = model_lcmm_multiple(formula_ttmmmg,data_mod,nclass = 5)
summarytable(model_ttmmmg_2,model_ttmmmg_3,model_ttmmmg_4,model_ttmmmg_5)
```


```{r}
model_ttmg_3$call$fixed = formula_ttmg
model_ttmm_3$call$fixed = formula_ttmm
model_mgmm_2$call$fixed = formula_mmmg
pred_ttmg = model_predict(model_ttmg_3,newdata)
pred_ttmm = model_predict(model_ttmm_3,newdata)
pred_mgmm = model_predict(model_mgmm_2,newdata)
plot(pred_ttmg,main="Tour de taille + masse grasse")
plot(pred_ttmm,main="Tour de taille + masse musculaire")
plot(pred_mgmm,main="Masse grasse + masse musculaire")
```

<!-- On prend que trois classes  -->

<!-- ```{r} -->
<!-- model_ttmmmg_3$call$fixed = formula_ttmmmg -->
<!-- model_predict(model_ttmmmg_3,newdata) -->
<!-- ``` -->










